source-file $HOME/.config/tmux/configs.d/*

# --- Tmux Plugin Manager --- #
# Define the plugin manager and where plugins will be loaded
set -g @plugin 'tmux-plugins/tpm'          # Load the plugin manager
# set -g @plugin 'tmux-plugins/tmux-resurrect'  # Plugin to restore tmux sessions
# set -g @plugin 'tmux-plugins/tmux-continuum' # Plugin for automatic session backup
set -g @plugin "nordtheme/tmux"

# Tmux Plugin Manager (TPM)
set -g @plugin 'tmux-plugins/tmux-sensible'    # A collection of tmux defaults
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'  # Highlight the current tmux prefix key


# Set status line for prefix-highlight
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_output_prefix 'PREFIX: '        

set -g @prefix_highlight_fg 'colour15'
set -g @prefix_highlight_bg 'colour4'
set -g @prefix_highlight_copy_mode_fg 'colour0'
set -g @prefix_highlight_copy_mode_bg 'colour3'

set -g status-right '#{prefix_highlight} | %a %Y-%m-%d %H:%M'


# Setup for resurrect
# set -g @resurrect-dir '~/.config/tmux/resurrect'
# set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'
# set -g @continuum-save-interval '15'   # in minutes


# Initialize TPM
run '~/.config/tmux/plugins/tpm/tpm'
